#define LUNGHEZZA_PESCE 2
#define DIM_BUCA 6.f
#define Spazio_Vitale 0.5f
#define MinDist 0
#define massa 1
#define DIMARR 3
#define dt 0.01
#define LateralDistance 4
#define VerticalDistance 2
#define FISHNUMBER 10
#define SCHOOLNUMBER 10