#define LUNGHEZZA_PESCE 2
#define DIM_BUCA 6.f
#define Spazio_Vitale 0.5f
#define MinDist 1000
#define massa 1
#define DIMARR 3
#define dt 0.01
#define LateralDistance 5
#define VerticalDistance 3
#define FISHNUMBER 5
#define SCHOOLNUMBER 5